name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Ajusta la rama principal según tu configuración
  pull_request:
    branches:
      - main  # Ajusta la rama principal según tu configuración

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurar el entorno de Java (si es necesario)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      # Ejecutar el análisis de SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
